# Generated by Django 3.2.6 on 2021-08-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_predictor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
